### ISSUE TITLE
Good morning!

### ISSUE THREAD

**Issue by szepeviktor** [khromov/wp-query-monitor-included-files#1]
Your plugin is very similar to mine:
https://wordpress.org/plugins/whats-running/

**Comment by khromov** [comment]
Hey Viktor,

Looks so! I gave a fairly length answer here:  
https://github.com/johnbillion/query-monitor/issues/61

Let me know if you wish to contribute in any way.

**Comment by szepeviktor** [comment]
[Groupping](https://github.com/johnbillion/query-monitor/issues/61#issuecomment-50183118) seem very-very useful, however will not show the load order.

**Comment by khromov** [comment]
@szepeviktor I was thinking both could be available. :)
