### ISSUE TITLE
Output of included files missing since 1.3

### ISSUE THREAD

**Issue by sun** [khromov/wp-query-monitor-included-files#3]
Problem
- The Included Files pane only shows the total summary since 1.3, but no list of the actually included files.

Cause
- Since https://github.com/khromov/wp-query-monitor-included-files/commit/86b02c3e080946a606fcf4bfa85cae87452a1bd3 the plugin only registers a single pane but outputs the multiple panes within:
    https://github.com/khromov/wp-query-monitor-included-files/blob/86b02c3e080946a606fcf4bfa85cae87452a1bd3/classes/QM_Output_IncludedFiles.class.php#L24
    https://github.com/khromov/wp-query-monitor-included-files/blob/86b02c3e080946a606fcf4bfa85cae87452a1bd3/classes/QM_Output_IncludedFiles.class.php#L61
    https://github.com/khromov/wp-query-monitor-included-files/blob/86b02c3e080946a606fcf4bfa85cae87452a1bd3/classes/QM_Output_IncludedFiles.class.php#L108

- Only the first is toggled into view when clicking on the pane in the query-monitor menu. The others are automatically hidden, because they do not match the menu.

Workaround
- Use the browser console to remove `display: none` from the additional output panes/containers to see the actual list of included files.

Proposed solution
1. Move the totals into Query Monitor's main summary/dashboard pane (not as a table but adding to one of the summary columns instead).

2. Show the aggregated list on the current menu item.

3. Add a submenu item to see the full list.

**Comment by khromov** [comment]
Thanks for the detailed report @sun , I swear this worked when I wrote the code ~7 years ago. 😅 

After the latest commit all of the output (totals / includes by component / files list) should render in the registered pane.

Open to PRs with further improvements!
